import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  technews: [
    {
      type: "category",
      label: "2026",
      link: {
        type: "generated-index",
        slug: "technews/2026", // サイトで出力させたいURL
      },
      items: [
        {
          type: "autogenerated",
          dirName: "technews/2026", // リポジトリのディレクトリを指定
        },
      ],
    },
  ],
  books: [
    {
      type: "category",
      label: "Books",
      link: {
        type: "generated-index",
        slug: "books", // サイトで出力させたいURL
      },
      items: [
        {
          type: "autogenerated",
          dirName: "books", // リポジトリのディレクトリを指定
        },
      ],
    }
  ]
};

export default sidebars;
